{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMaKuuNCay1PZEyNcAJKHzk",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/furkandr01/python_data_science/blob/main/Odev2.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "wzN_Dv7lI78k",
        "outputId": "3b8d6f72-5f47-4867-ddc3-ad1ca31249e3"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "1 . Kitap Ekle\n",
            "2 . Kitap Çıkar\n",
            "3 . Kitapları Listele\n",
            "4 . Çıkış\n",
            "Lütfen yapmak istediğiniz işlem numarasını giriniz: 3\n",
            "1 . Kürk Mantolu Madonna , Sebahattin Ali\n",
            "2 . İçimizdeki Şeytan , Sebahattin Ali\n",
            "3 . Tutunamayanlar , Oğuz Atay\n",
            "4 . Çalıkuşu , Reşat Nuri Güntekin\n",
            "5 . Suç ve Ceza , Dostoevsky\n",
            "6 . Savaş ve Barış , Tolstoy\n",
            "7 . Kuyucaklı Yusuf , Sebahattin Ali\n",
            "\n",
            "\n",
            "1 . Kitap Ekle\n",
            "2 . Kitap Çıkar\n",
            "3 . Kitapları Listele\n",
            "4 . Çıkış\n",
            "Lütfen yapmak istediğiniz işlem numarasını giriniz: 1\n",
            "Eklemek istediğiniz kitabın adını giriniz: Münevver\n",
            "Eklemek istediğiniz kitabın yazarını adını giriniz: Beyza\n",
            "Münevver kitabı listeye eklendi\n",
            "1 . Kitap Ekle\n",
            "2 . Kitap Çıkar\n",
            "3 . Kitapları Listele\n",
            "4 . Çıkış\n",
            "Lütfen yapmak istediğiniz işlem numarasını giriniz: 3\n",
            "1 . Kürk Mantolu Madonna , Sebahattin Ali\n",
            "2 . İçimizdeki Şeytan , Sebahattin Ali\n",
            "3 . Tutunamayanlar , Oğuz Atay\n",
            "4 . Çalıkuşu , Reşat Nuri Güntekin\n",
            "5 . Suç ve Ceza , Dostoevsky\n",
            "6 . Savaş ve Barış , Tolstoy\n",
            "7 . Kuyucaklı Yusuf , Sebahattin Ali\n",
            "8 . Münevver , Beyza\n",
            "\n",
            "\n",
            "1 . Kitap Ekle\n",
            "2 . Kitap Çıkar\n",
            "3 . Kitapları Listele\n",
            "4 . Çıkış\n",
            "Lütfen yapmak istediğiniz işlem numarasını giriniz: 1\n",
            "Eklemek istediğiniz kitabın adını giriniz: Test\n",
            "Eklemek istediğiniz kitabın yazarını adını giriniz: Cem Karaca\n",
            "Test kitabı listeye eklendi\n",
            "1 . Kitap Ekle\n",
            "2 . Kitap Çıkar\n",
            "3 . Kitapları Listele\n",
            "4 . Çıkış\n",
            "Lütfen yapmak istediğiniz işlem numarasını giriniz: 3\n",
            "1 . Kürk Mantolu Madonna , Sebahattin Ali\n",
            "2 . İçimizdeki Şeytan , Sebahattin Ali\n",
            "3 . Tutunamayanlar , Oğuz Atay\n",
            "4 . Çalıkuşu , Reşat Nuri Güntekin\n",
            "5 . Suç ve Ceza , Dostoevsky\n",
            "6 . Savaş ve Barış , Tolstoy\n",
            "7 . Kuyucaklı Yusuf , Sebahattin Ali\n",
            "8 . Münevver , Beyza\n",
            "9 . Test , Cem Karaca\n",
            "\n",
            "\n",
            "1 . Kitap Ekle\n",
            "2 . Kitap Çıkar\n",
            "3 . Kitapları Listele\n",
            "4 . Çıkış\n",
            "Lütfen yapmak istediğiniz işlem numarasını giriniz: 2\n",
            "Lütfen almak istediğiniz kitabın yazarını giriniz: beyza\n",
            "1 . Münevver\n",
            "Lütfen almak istediğiniz kitabın numarasını giriniz: 1\n",
            "Münevver adlı kitabı aldınız. İyi okumalar.\n",
            "1 . Kitap Ekle\n",
            "2 . Kitap Çıkar\n",
            "3 . Kitapları Listele\n",
            "4 . Çıkış\n",
            "Lütfen yapmak istediğiniz işlem numarasını giriniz: 3\n",
            "1 . Kürk Mantolu Madonna , Sebahattin Ali\n",
            "2 . İçimizdeki Şeytan , Sebahattin Ali\n",
            "3 . Tutunamayanlar , Oğuz Atay\n",
            "4 . Çalıkuşu , Reşat Nuri Güntekin\n",
            "5 . Suç ve Ceza , Dostoevsky\n",
            "6 . Savaş ve Barış , Tolstoy\n",
            "7 . Kuyucaklı Yusuf , Sebahattin Ali\n",
            "8 . Test , Cem Karaca\n",
            "\n",
            "\n",
            "1 . Kitap Ekle\n",
            "2 . Kitap Çıkar\n",
            "3 . Kitapları Listele\n",
            "4 . Çıkış\n",
            "Lütfen yapmak istediğiniz işlem numarasını giriniz: 2\n",
            "Lütfen almak istediğiniz kitabın yazarını giriniz: cem Karaca\n",
            "1 . Test\n",
            "Lütfen almak istediğiniz kitabın numarasını giriniz: 1\n",
            "Test adlı kitabı aldınız. İyi okumalar.\n",
            "1 . Kitap Ekle\n",
            "2 . Kitap Çıkar\n",
            "3 . Kitapları Listele\n",
            "4 . Çıkış\n",
            "Lütfen yapmak istediğiniz işlem numarasını giriniz: 3\n",
            "1 . Kürk Mantolu Madonna , Sebahattin Ali\n",
            "2 . İçimizdeki Şeytan , Sebahattin Ali\n",
            "3 . Tutunamayanlar , Oğuz Atay\n",
            "4 . Çalıkuşu , Reşat Nuri Güntekin\n",
            "5 . Suç ve Ceza , Dostoevsky\n",
            "6 . Savaş ve Barış , Tolstoy\n",
            "7 . Kuyucaklı Yusuf , Sebahattin Ali\n",
            "\n",
            "\n",
            "1 . Kitap Ekle\n",
            "2 . Kitap Çıkar\n",
            "3 . Kitapları Listele\n",
            "4 . Çıkış\n",
            "Lütfen yapmak istediğiniz işlem numarasını giriniz: 2\n",
            "Lütfen almak istediğiniz kitabın yazarını giriniz: sebahattin ali\n",
            "1 . Kürk Mantolu Madonna\n",
            "2 . İçimizdeki Şeytan\n",
            "3 . Kuyucaklı Yusuf\n",
            "Lütfen almak istediğiniz kitabın numarasını giriniz: 3\n",
            "Kuyucaklı Yusuf adlı kitabı aldınız. İyi okumalar.\n",
            "1 . Kitap Ekle\n",
            "2 . Kitap Çıkar\n",
            "3 . Kitapları Listele\n",
            "4 . Çıkış\n",
            "Lütfen yapmak istediğiniz işlem numarasını giriniz: 4\n"
          ]
        }
      ],
      "source": [
        "library = [\n",
        "    (\"Kürk Mantolu Madonna\",\"Sebahattin Ali\"),\n",
        "    (\"İçimizdeki Şeytan\",\"Sebahattin Ali\"),\n",
        "    (\"Tutunamayanlar\",\"Oğuz Atay\"),\n",
        "    (\"Çalıkuşu\",\"Reşat Nuri Güntekin\"),\n",
        "    (\"Suç ve Ceza\",\"Dostoevsky\"),\n",
        "    (\"Savaş ve Barış\",\"Tolstoy\"),\n",
        "    (\"Kuyucaklı Yusuf\",\"Sebahattin Ali\"),\n",
        "    (\"Malcom X\",\"Alex Haley\"),\n",
        "    (\"Sefiller\",\"Victor Hugo\")\n",
        "]\n",
        "\n",
        "menu = [\"Kitap Ekle\", \"Kitap Çıkar\", \"Kitapları Listele\", \"Çıkış\"]\n",
        "\n",
        "operation = 0\n",
        "while operation != 4:\n",
        "  y = 1\n",
        "  for x in menu:\n",
        "    print(y,\".\",x)\n",
        "    y += 1\n",
        "  operation = int(input(\"Lütfen yapmak istediğiniz işlem numarasını giriniz: \"))\n",
        "  if operation == 1:\n",
        "    newBookName = input(\"Eklemek istediğiniz kitabın adını giriniz: \")\n",
        "    newBookAuthor = input(\"Eklemek istediğiniz kitabın yazarını adını giriniz: \")\n",
        "    book = (newBookName, newBookAuthor)\n",
        "    if book not in library:\n",
        "      library.append(book)\n",
        "      print(newBookName,\"kitabı listeye eklendi\")\n",
        "    else:\n",
        "      print(\"Bu kitap zaten kütüphanede kayıtlı.\")\n",
        "  elif operation == 2:\n",
        "      searchAuthor = input(\"Lütfen almak istediğiniz kitabın yazarını giriniz: \").casefold()\n",
        "      foundBooks = []\n",
        "      z = 1\n",
        "      for book in library:\n",
        "        if book[1].casefold() == searchAuthor:\n",
        "          print(z,\".\",book[0])\n",
        "          foundBooks.append(book)\n",
        "          z += 1\n",
        "      if len(foundBooks) == 0:\n",
        "        print(\"Bu yazara ait kitap bulunamadı!\")\n",
        "      else:\n",
        "        selectedBook = int(input(\"Lütfen almak istediğiniz kitabın numarasını giriniz: \"))\n",
        "        if selectedBook<1 or selectedBook > len(foundBooks):\n",
        "          print(\"Geçersiz seçim.\")\n",
        "        else:\n",
        "          library.remove(foundBooks[selectedBook - 1])\n",
        "          print(foundBooks[selectedBook - 1][0],\"adlı kitabı aldınız. İyi okumalar.\")\n",
        "  elif operation == 3:\n",
        "    a = 1\n",
        "    for book in library:\n",
        "      print(a,\".\", book[0] , \",\" , book[1])\n",
        "      a += 1\n",
        "    print(\"\\n\")"
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "-PVZ1uSbvXyH"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}